version: '3'
services:
  nginx:
    build: nginx/
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - image-volume:/usr/share/nginx/html/images
  app:
    build: app/
    ports:
      - "3031:3031"
    environment:
      FLASK_DEBUG: 1
      GALLERY_HOSTNAME: "localhost:8080"
    volumes:
      - image-volume:/usr/share/nginx/html/images
volumes:
  image-volume:
    external: true
